#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$PLUGIN_BASE_PATH/deploy-from-registry/internal-functions"

cmd-deploy-from-registry-get-remote-image-repo() {
  local cmd="${PLUGIN_COMMAND_PREFIX}:get-remote-image-repo" argv=("$@"); [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP="$1"
  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_app_name "$APP"

  VALUE="$(fn-config-read "$APP" "remote-image-repo")"
  [[ -z "$VALUE" ]] && dokku_log_fail "The remote image repo is not set for this $APP"
  
  dokku_log_quiet "$VALUE"
}

cmd-deploy-from-registry-get-remote-image-repo "$@"
