#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$PLUGIN_BASE_PATH/deploy-from-registry/internal-functions"

cmd-deploy-from-registry-set-remote-image-repo() {
  local cmd="${PLUGIN_COMMAND_PREFIX}:set-remote-image-repo" argv=("$@"); [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP="$1" VALUE="$2"
  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  [[ -z "$VALUE" ]] && dokku_log_fail "Please specify a value"
  verify_app_name "$APP"

  fn-verify-image-repo "$VALUE"

  # For idempotence
  CURRENT_VALUE="$(fn-config-read "$APP" "remote-image-repo")"
  if [[ "$CURRENT_VALUE" == "$VALUE" ]]; then
  	dokku_log_quiet "The remote image repo for $APP was already \"$(fn-config-read "$APP" "remote-image-repo")\""
  	exit 2
  fi

  fn-config-write "$APP" "remote-image-repo" "$VALUE"
  dokku_log_info1 "The remote image repo for $APP is now \"$(fn-config-read "$APP" "remote-image-repo")\""
}

cmd-deploy-from-registry-set-remote-image-repo "$@"
