#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$PLUGIN_BASE_PATH/deploy-from-registry/internal-functions"

cmd-deploy-from-registry-unset-remote-image-repo() {
  local cmd="${PLUGIN_COMMAND_PREFIX}:unset-remote-image-repo" argv=("$@"); [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP="$1"
  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_app_name "$APP"

  # For idempotence
  CURRENT_VALUE="$(fn-config-read "$APP" "remote-image-repo")"
  if [[ -z "$CURRENT_VALUE" ]]; then
  	dokku_log_quiet "The remote image repo for $APP was already not set"
  	exit 2
  fi

  fn-config-delete "$APP" "remote-image-repo"
  dokku_log_info1 "The remote image repo for $APP has been unset"
}

cmd-deploy-from-registry-unset-remote-image-repo "$@"
